### ISSUE TITLE
TT4: Put Property

### ISSUE THREAD

**Issue by UnTamedLaw** [North-Seattle-College/ad440-winter2020-thursday-repo#145]

**Comment by miscdats** [comment]
[related task](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/144)

Using the link and data values provided in wiki for function in format as such:
```
{
    "property_name": "main st",
    "property_type": 1,
    "property_address": "999 Main ST",
    "property_city": "Seattle",
    "property_state": "WA",
    "property_zip": "98105",
    "property_country": "USA"
}
```

As well as attempting different variations of data.

Attempted PUT request using auth credentials to [endpoint](https://api.2edusite.com/feature-sprint3/property/47)
- expected: status, related info

- actual : JSON response with status 200 OK and message with trace
  ```{
    "errorType": "Error",
    "errorMessage": "ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`keymanagement`.`property`, CONSTRAINT `property_ibfk_1` FOREIGN KEY (`property_type_id`) REFERENCES `propertytype` (`property_type_id`) ON DELETE NO ACTION)",
    "trace": [
        "Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`keymanagement`.`property`, CONSTRAINT `property_ibfk_1` FOREIGN KEY (`property_type_id`) REFERENCES `propertytype` (`property_type_id`) ON DELETE NO ACTION)",
        "    at Query.Sequence._packetToError (/var/task/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)",
        "    at Query.ErrorPacket (/var/task/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)",
        "    at Protocol._parsePacket (/var/task/node_modules/mysql/lib/protocol/Protocol.js:291:23)",
        "    at Parser._parsePacket (/var/task/node_modules/mysql/lib/protocol/Parser.js:433:10)",
        "    at Parser.write (/var/task/node_modules/mysql/lib/protocol/Parser.js:43:10)",
        "    at Protocol.write (/var/task/node_modules/mysql/lib/protocol/Protocol.js:38:16)",
        "    at Socket.<anonymous> (/var/task/node_modules/mysql/lib/Connection.js:88:28)",
        "    at Socket.<anonymous> (/var/task/node_modules/mysql/lib/Connection.js:526:10)",
        "    at Socket.emit (events.js:223:5)",
        "    at addChunk (_stream_readable.js:309:12)",
        "    --------------------",
        "    at Protocol._enqueue (/var/task/node_modules/mysql/lib/protocol/Protocol.js:144:48)",
        "    at Connection.query (/var/task/node_modules/mysql/lib/Connection.js:198:25)",
        "    at Runtime.exports.handler (/var/task/putProperty.js:62:16)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}```
