### ISSUE TITLE
TT5: Get KeyHolder By ID

### ISSUE THREAD

**Issue by UnTamedLaw** [North-Seattle-College/ad440-winter2020-thursday-repo#147]

**Comment by anuslorah** [comment]
**Test Objective:**
behavior of GET/keyholder/{id}
**Environment**
https://reqbin.com/

**perfect request**
GET
https://api.2edusite.com/feature-sprint3/keyholder/8

**Expected:**
response status code 200
response body json 
{
"keyholder_id": 8,
 first_name": "dereje",
 "last_name": "ds",
 "email": "abc@xyz.com",
 "phone": "2061234567",
 "keyholder_type_id": 1,
 "keyholder_type": "management company"
 }

**Received:**
{
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: Unexpected end of input",
    "trace": ["Runtime.UserCodeSyntaxError: SyntaxError: Unexpected end of input", "    at _loadUserApp (/var/runtime/UserFunction.js:98:13)", "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)", "    at Object.<anonymous> (/var/runtime/index.js:43:30)", "    at Module._compile (internal/modules/cjs/loader.js:955:30)", "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)", "    at Module.load (internal/modules/cjs/loader.js:811:32)", "    at Function.Module._load (internal/modules/cjs/loader.js:723:14)", "    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)", "    at internal/main/run_main_module.js:17:11"]
}
